dependencies:
  config:
    - paragraphs.paragraphs_type.blockquote
settings:
  handler_settings:
    target_bundles:
      blockquote: blockquote
    target_bundles_drag_drop:
      blockquote:
        enabled: true
        weight: 0
